
export const superTypes = [
  "ACE SPEC", "BREAK", "Baby",
  "Basic", "EX", "Eternamax",
  "Fusion Strike", "GX",
  "Goldenrod Game Corner",
  "Item", "LEGEND", "Level-Up",
  "MEGA", "Pokémon Tool",
  "Pokémon Tool F", "Prime",
  "Prism Star", "Radiant",
  "Rapid Strike", "Restored",
  "Rocket's Secret Machine", "SP",
  "Single Strike", "Special",
  "Stadium", "Stage 1", "Stage 2",
  "Star", "Supporter", "TAG TEAM",
  "Team Plasma", "Technical Machine",
  "Tera", "Tera ex", "Ultra Beast",
  "V", "V-UNION", "VMAX", "VSTAR",
  "ex", "ex-3"];

export const cardColors = [
  "Colorless",
  "Darkness",
  "Dragon",
  "Fairy",
  "Fighting",
  "Fire",
  "Grass",
  "Lightning",
  "Metal",
  "Psychic",
  "Water"
];



export const deck = [
  "https://images.pokemontcg.io/swsh12pt5gg/GG50_hires.png",
  "https://images.pokemontcg.io/swsh12pt5gg/GG50_hires.png",
  "https://images.pokemontcg.io/swsh12pt5gg/GG50_hires.png",
  "https://images.pokemontcg.io/swsh10/98_hires.png",
  "https://images.pokemontcg.io/swsh10/98_hires.png",
  "https://images.pokemontcg.io/swsh10/98_hires.png",
  "https://images.pokemontcg.io/swsh10/46_hires.png",
  "https://images.pokemontcg.io/swsh6/97_hires.png",
  "https://images.pokemontcg.io/swshp/SWSH125_hires.png",
  "https://images.pokemontcg.io/swshp/SWSH125_hires.png",
  "https://images.pokemontcg.io/swsh8/77_hires.png",
  "https://images.pokemontcg.io/swsh9/155_hires.png",
  "https://images.pokemontcg.io/sv1/240_hires.png",
  "https://images.pokemontcg.io/sv1/240_hires.png",
  "https://images.pokemontcg.io/sv1/240_hires.png",
  "https://images.pokemontcg.io/sv1/240_hires.png",
  "https://images.pokemontcg.io/swsh6/217_hires.png",
  "https://images.pokemontcg.io/swsh10/188_hires.png",
  "https://images.pokemontcg.io/swsh11tg/TG24_hires.png",
  "https://images.pokemontcg.io/swsh9/186_hires.png",
  "https://images.pokemontcg.io/swsh9/186_hires.png",
  "https://images.pokemontcg.io/swsh9/186_hires.png",
  "https://images.pokemontcg.io/swsh9/186_hires.png",
  "https://images.pokemontcg.io/swsh8/230_hires.png",
  "https://images.pokemontcg.io/swsh8/230_hires.png",
  "https://images.pokemontcg.io/swsh8/230_hires.png",
  "https://images.pokemontcg.io/swsh8/230_hires.png",
  "https://images.pokemontcg.io/swsh10/214_hires.png",
  "https://images.pokemontcg.io/xy7/99_hires.png",
  "https://images.pokemontcg.io/swsh11/216_hires.png",
  "https://images.pokemontcg.io/swsh11/216_hires.png",
  "https://images.pokemontcg.io/swsh11/216_hires.png",
  "https://images.pokemontcg.io/swsh11/216_hires.png",
  "https://images.pokemontcg.io/swsh10/146_hires.png",
  "https://images.pokemontcg.io/swsh11/217_hires.png",
  "https://images.pokemontcg.io/swsh10/215_hires.png",
  "https://images.pokemontcg.io/swsh10/215_hires.png",
  "https://images.pokemontcg.io/swsh10/215_hires.png",
  "https://images.pokemontcg.io/swsh10/215_hires.png",
  "https://images.pokemontcg.io/pgo/68_hires.png",
  "https://images.pokemontcg.io/pgo/68_hires.png",
  "https://images.pokemontcg.io/sv1/255_hires.png",
  "https://images.pokemontcg.io/sv1/255_hires.png",
  "https://images.pokemontcg.io/xy2/92_hires.png",
  "https://images.pokemontcg.io/swsh8/225_hires.png",
  "https://images.pokemontcg.io/swsh8/225_hires.png",
  "https://images.pokemontcg.io/swsh8/225_hires.png",


  "https://images.pokemontcg.io/swsh7/236_hires.png",
  "https://images.pokemontcg.io/swsh7/236_hires.png",
  "https://images.pokemontcg.io/swsh7/236_hires.png",
  "https://images.pokemontcg.io/swsh7/236_hires.png",
  "https://images.pokemontcg.io/swsh7/236_hires.png",
  "https://images.pokemontcg.io/swsh7/236_hires.png",
  "https://images.pokemontcg.io/swsh7/236_hires.png",
  "https://images.pokemontcg.io/swsh7/236_hires.png",
  "https://images.pokemontcg.io/swsh7/236_hires.png",
  "https://images.pokemontcg.io/swsh7/236_hires.png",
  "https://images.pokemontcg.io/swsh7/236_hires.png",
  "https://images.pokemontcg.io/swsh7/236_hires.png",
  "https://images.pokemontcg.io/swsh7/236_hires.png",

]